CREATE TABLE Sheet1(--FahmiZainal VARCHAR(10),Column_2 VARCHAR(10));
INSERT INTO Sheet1 (--FahmiZainal,Column_2) VALUES 
('/*',''),
('SQL Notes ','This is based on Superstore Dataset across the globe'),
('To help Superstore better understand their data',' you will write queries that'),
('answer the questions below:',''),
('1. Which products are made by Xerox(hint: product_name contains',''),
('xerox)?',''),
('2. How many countries are in our Western Europe sub-region?',''),
('3. How many customers in our consumer segment have names that start',''),
('with the letter “S”?',''),
('4. What is the total number of items (not orders) returned with some',''),
('reason given?',''),
('5. How many orders used Standard Shipping and a discount code?',''),
('*/',''),
('SELECT DISTINCT(sub_category)',''),
('FROM products',''),
('WHERE product_name ILIKE ‘%xerox%’;',''),
('--Answer paper and machines',''),
('SELECT COUNT(DISTINCT country)',''),
('FROM regions',''),
('WHERE sub_region = ‘Western Europe’;',''),
('--Answer 6',''),
('SELECT COUNT(DISTINCT customer_name)',''),
('FROM customers',''),
('WHERE customer_name LIKE ‘S%’ AND segment =’Consumer’;',''),
('--Answer 35',''),
('SELECT SUM(return_quantity)',''),
('FROM returns',''),
('WHERE reason_returned !=’Not Given’;',''),
('--Answer 31781',''),
('SELECT COUNT(DISTINCT order_id)',''),
('FROM orders',''),
('WHERE ship_mode =”Standard Class’ AND discount > 0',''),
('--Answer 385615','');